version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mi_base
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redlocal

  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mi_base
      AUTOR: Omar Jaimes and Bryan Vera
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - redlocal

networks:
  redlocal:

volumes:
  postgres_data:
